In [1]:
pip install nltk --upgrade


     |████████████████████████████████| 1.5MB 2.9MB/s 
  Stored in directory: /root/.cache/pip/wheels/54/40/b7/c56ad418e6cd4d9e1e594b5e138d1ca6eec11a6ee3d464e5bb
Successfully built nltk
  Found existing installation: nltk 3.2.5
    Uninstalling nltk-3.2.5:
      Successfully uninstalled nltk-3.2.5


In [2]:
pip install vaderSentiment

     |████████████████████████████████| 133kB 2.8MB/s 


In [3]:
pip install numpy --upgrade

Requirement already up-to-date: numpy in /usr/local/lib/python3.6/dist-packages (1.16.4)


In [4]:
pip install scipy --upgrade 

Requirement already up-to-date: scipy in /usr/local/lib/python3.6/dist-packages (1.3.0)


In [5]:
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all


       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package brown to /root/nltk_data...
       |   Unzipping corpora/brown.zip.
       | Downloading package brown_tei to /root/nltk_data...
       |   Unzipping corpora/brown_tei.zip.
       | Downloading package cess_cat to /root/nltk_data...
       |   Unzipping corpora/cess_cat.zip.
       | Downloading package cess_esp to /root/nltk_data...
       |   Unzipping corpora/cess_esp.zip.
       | Downloading package chat80 to /root/nltk_data...
       |   Unzipping corpora/chat80.zip.
       | Downloading package city_database to /root/nltk_data...
       |   Unzipping corpora/city_database.zip.
       | Downloading package cmudict to /root/nltk_data...
  


---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [0]:
import numpy as np

In [0]:
#VADER Sentiment Analysis. VADER (Valence Aware Dictionary and sEntiment Reasoner) is a lexicon and rule-based sentiment analysis tool that is specifically attuned to sentiments expressed in social media, and works well on texts from other domains.

from nltk.sentiment import SentimentAnalyzer
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [8]:
"""
sid = SentimentIntensityAnalyzer()
for sentence in sentences:
    ss = sid.polarity_scores(sentence)
    for k in sorted(ss):
      print('{0}: {1}, '.format(k, ss[k]), end='')
    print()
"""

"\nsid = SentimentIntensityAnalyzer()\nfor sentence in sentences:\n    ss = sid.polarity_scores(sentence)\n    for k in sorted(ss):\n      print('{0}: {1}, '.format(k, ss[k]), end='')\n    print()\n"

In [9]:
from nltk.tokenize import sent_tokenize, word_tokenize,line_tokenize

f = open("2012LTinsultsLKML.tsv.txt", "r")
all_text = f.read()
print(all_text)

# Author: Squire, M. & Gazda, R.
# License: Open Database License 1.0
# This data 2012LTinsultsLKML.tsv.txt is made available under the 
# Open Database License: http://opendatacommons.org/licenses/odbl/1.0/. 
# Any rights in individual contents of the database are licensed under the 
# Database Contents License: http://opendatacommons.org/licenses/dbcl/1.0/ 
#
# filename: 2012LTinsultsLKML.tsv.txt
# explanation: 
# This data set is part of a larger group of data sets
# described in the paper below, and hosted on the FLOSSmole.org site. 
# Contains insults gleaned from messages sent to the LKML mailing list by 
# Linus Torvalds during the year 2012
#
# fields:
# date: this is the date the original email was sent
# markmail permalink: this is a permalink to the email on markmail (for easy reading)
# type: this is our code for what type of insult this is
# mail excerpt: this is the fragment of the email containing the insult(s). 
# Ellipses (...) have been added where necessary.
#
# Plea

In [10]:
#for i in word_tokenize(all_text):
 # print(i)
print(word_tokenize(all_text))

['#', 'Author', ':', 'Squire', ',', 'M.', '&', 'Gazda', ',', 'R.', '#', 'License', ':', 'Open', 'Database', 'License', '1.0', '#', 'This', 'data', '2012LTinsultsLKML.tsv.txt', 'is', 'made', 'available', 'under', 'the', '#', 'Open', 'Database', 'License', ':', 'http', ':', '//opendatacommons.org/licenses/odbl/1.0/', '.', '#', 'Any', 'rights', 'in', 'individual', 'contents', 'of', 'the', 'database', 'are', 'licensed', 'under', 'the', '#', 'Database', 'Contents', 'License', ':', 'http', ':', '//opendatacommons.org/licenses/dbcl/1.0/', '#', '#', 'filename', ':', '2012LTinsultsLKML.tsv.txt', '#', 'explanation', ':', '#', 'This', 'data', 'set', 'is', 'part', 'of', 'a', 'larger', 'group', 'of', 'data', 'sets', '#', 'described', 'in', 'the', 'paper', 'below', ',', 'and', 'hosted', 'on', 'the', 'FLOSSmole.org', 'site', '.', '#', 'Contains', 'insults', 'gleaned', 'from', 'messages', 'sent', 'to', 'the', 'LKML', 'mailing', 'list', 'by', '#', 'Linus', 'Torvalds', 'during', 'the', 'year', '2012', '

In [0]:
t_hash = "#"
for i in line_tokenize(all_text):
  if t_hash not in i:
    print(i)
      

In [0]:
# preprocessing the text to remove the unwanted part and making the whole text in lowercase 
import re
def pre_process(text):
    
    # lowercase
    text=text.lower()
    
    #remove tags
    text=re.sub("<!--?.*?-->","",text)
    """
    # remove special characters and digits
    text=re.sub("(\\d|\\W)+"," ",text)
    """
    return text

In [0]:
def get_index(file):
  new_index = 0
  for line in file:
    new_index = new_index +1
  return(new_index)    
    


In [0]:
# need to do stemming and Lemmatization

from nltk.stem import PorterStemmer

ps = PorterStemmer()


In [0]:
sid = SentimentIntensityAnalyzer()


In [0]:
def get_sentiment(line):
  ss = sid.polarity_scores(line)
  
  count = 0
  output = np.zeros(4)
  for k in ss:
    count = count + 1
    if count % 4 == 0 :
      output[3] = ss[k]
      print('{0}: {1}, '.format(k, ss[k]), end='')
      #print(k)
    
    elif count % 3 == 0:
      output[2] = ss[k]
      print('{0}: {1}, '.format(k, ss[k]), end='')
      #print(k)
    elif count%2 == 0:
      output[1] = ss[k]
      print('{0}: {1}, '.format(k, ss[k]), end='')
      #print(k)
    else:
      output[0] = ss[k]
      print('{0}: {1}, '.format(k, ss[k]), end='')
      #print(k)
  #print(ss[k])
  #print('{0}: {1}, '.format(k, ss[k]), end='')
  
  return output
      
    #print('{0}: {1}, '.format(k, ss[k]), end='')

    #print(ss[k])
  #print()
  #print(new_line)


In [17]:
from nltk.corpus import stopwords


stop_words = set(stopwords.words("english"))

webpage = "http" # since the comments rows in the file have a weblink available we extract the rows using this

new_fout = open("comments.txt","w")
sentiment_file = open("sentiment_value.txt","w")


index = 0

from __future__ import print_function
with open ("2012LTinsultsLKML.tsv.txt") as fin, open("positive_tokens.txt","w+") as fout:
    for line in fin:
      if t_hash not in line[0:2]:
        
        tokens = word_tokenize(line)
        
        if webpage in tokens:
          print(line[64:],end = '',file = new_fout)
          new_line = pre_process(line[64:]) # line changed to temp_sentence
          
          index = index + 1 
          out_sen = []
          out_sen = get_sentiment(line[64:])
          new_tokens = word_tokenize(new_line) 
                    
          filtered_sentence = []
          
          for w in new_tokens:
            if w not in stop_words:
              better_words = ps.stem(w)
              #print(w, " : ", better_words)
              filtered_sentence.append(better_words)
              #print(' '.join(new_tokens), end='\n', file=fout)
          
          print(filtered_sentence, end='\n', file=fout)
          
          print(out_sen,end = '\n',file = sentiment_file) 

neg: 0.39, neu: 0.61, pos: 0.0, compound: -0.8256, neg: 0.308, neu: 0.692, pos: 0.0, compound: -0.9711, neg: 0.211, neu: 0.695, pos: 0.094, compound: -0.7757, neg: 0.148, neu: 0.82, pos: 0.032, compound: -0.874, neg: 0.097, neu: 0.802, pos: 0.101, compound: -0.2127, neg: 0.226, neu: 0.674, pos: 0.1, compound: -0.9675, neg: 0.157, neu: 0.816, pos: 0.027, compound: -0.9772, neg: 0.437, neu: 0.563, pos: 0.0, compound: -0.8709, neg: 0.236, neu: 0.764, pos: 0.0, compound: -0.937, neg: 0.329, neu: 0.671, pos: 0.0, compound: -0.6597, neg: 0.057, neu: 0.771, pos: 0.173, compound: 0.6278, neg: 0.454, neu: 0.546, pos: 0.0, compound: -0.3597, neg: 0.364, neu: 0.553, pos: 0.083, compound: -0.9848, neg: 0.16, neu: 0.79, pos: 0.05, compound: -0.6486, neg: 0.239, neu: 0.741, pos: 0.02, compound: -0.9699, neg: 0.091, neu: 0.798, pos: 0.111, compound: 0.1436, neg: 0.267, neu: 0.576, pos: 0.157, compound: -0.5868, neg: 0.435, neu: 0.565, pos: 0.0, compound: -0.875, neg: 0.321, neu: 0.596, pos: 0.083, co

In [18]:
print (index)

108


In [19]:
"""
# delete this cell after use

vals = open("sentiment_value.txt","r")
values = vals.read()
print(values)
"""

'\n# delete this cell after use\n\nvals = open("sentiment_value.txt","r")\nvalues = vals.read()\nprint(values)\n'

In [0]:
c_file = open("all_files.txt","r")

all_index = get_index(c_file)
c_file = open("all_files.txt","r")
f_matrix = np.zeros((all_index,5))
l_count = 0
for line in c_file:
  f_matrix[l_count][0:4] = get_sentiment(line)
  l_count = l_count + 1

print(f_matrix[200:300])

print(l_count)

In [21]:
"""
for sentence in new_fout:
  ss = sid.polarity_scores(sentence)
  for k in sorted(ss):
      print('{0}: {1}, '.format(k, ss[k]), end='')
  print()
"""  

"\nfor sentence in new_fout:\n  ss = sid.polarity_scores(sentence)\n  for k in sorted(ss):\n      print('{0}: {1}, '.format(k, ss[k]), end='')\n  print()\n"

In [22]:
from nltk.corpus import words
print (len(words.words()))


236736


In [0]:
# We will now implement TF IDF to obtain the features in a numeric form 

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()



In [0]:
new_file = open("positive_tokens.txt", "r")
X = vectorizer.fit_transform(new_file)

In [0]:
feature_file = open("positive_features.txt","w")
print(vectorizer.get_feature_names(),end = '\n',file = feature_file)

In [26]:
print(vectorizer.get_feature_names().index('idiot'))

360


In [27]:
print(X.toarray().shape)

(108, 892)


In [0]:
#named entity recognition


In [0]:
#====================================================================================================================================================================================================

In [29]:
pos_file = open("build_noname.txt","r")

pos_index = get_index(pos_file)

pos_file = open("build_noname.txt","r")
pos_sentiment = np.ones((pos_index,5))
pos_count = 0
for line in pos_file:
  pos_sentiment[pos_count,:][0:4] = get_sentiment(line)
  pos_count = pos_count + 1  
print(pos_sentiment.shape)  

pos_val_file = open("pos_val_file.txt","w+")
for item in pos_sentiment:
  pos_val_file.write("%s\n" % item)

neg: 0.096, neu: 0.84, pos: 0.065, compound: -0.6187, neg: 0.034, neu: 0.888, pos: 0.078, compound: 0.6858, neg: 0.0, neu: 0.803, pos: 0.197, compound: 0.7264, neg: 0.113, neu: 0.778, pos: 0.109, compound: 0.1424, neg: 0.0, neu: 0.435, pos: 0.565, compound: 0.6369, neg: 0.0, neu: 1.0, pos: 0.0, compound: 0.0, neg: 0.041, neu: 0.897, pos: 0.061, compound: 0.5699, neg: 0.0, neu: 0.917, pos: 0.083, compound: 0.6887, neg: 0.0, neu: 0.753, pos: 0.247, compound: 0.3182, neg: 0.0, neu: 0.932, pos: 0.068, compound: 0.4588, neg: 0.041, neu: 0.909, pos: 0.05, compound: 0.0783, neg: 0.117, neu: 0.726, pos: 0.157, compound: 0.8459, neg: 0.0, neu: 0.829, pos: 0.171, compound: 0.7506, neg: 0.042, neu: 0.895, pos: 0.064, compound: 0.784, neg: 0.044, neu: 0.88, pos: 0.077, compound: 0.8626, neg: 0.0, neu: 0.85, pos: 0.15, compound: 0.9428, neg: 0.103, neu: 0.845, pos: 0.051, compound: -0.6008, neg: 0.09, neu: 0.79, pos: 0.12, compound: -0.1431, neg: 0.0, neu: 0.931, pos: 0.069, compound: 0.2933, neg: 

In [30]:
print(pos_sentiment[0:,4])

[1. 1. 1. ... 1. 1. 1.]


In [31]:
X = [[0, 0], [1, 1]]
     
print(X)     
Y = np.zeros((2,2))
Y[0][0] = 5
print(Y)


[[0, 0], [1, 1]]
[[5. 0.]
 [0. 0.]]


In [32]:
new_feature_matrix = np.concatenate((f_matrix, pos_sentiment))
print(f_matrix.shape)
print(pos_sentiment.shape)
print(new_feature_matrix)


(309, 5)
(6794, 5)
[[ 0.39    0.61    0.     -0.8256  0.    ]
 [ 0.308   0.692   0.     -0.9711  0.    ]
 [ 0.211   0.695   0.094  -0.7757  0.    ]
 ...
 [ 0.      1.      0.      0.      1.    ]
 [ 0.      1.      0.      0.      1.    ]
 [ 0.037   0.696   0.267   0.873   1.    ]]


In [33]:
labels = new_feature_matrix[0:,4]
final_features = new_feature_matrix[0:,0:4]
print(final_features)
print(labels)
from sklearn import svm

clf = svm.SVC(gamma='scale')
clf.fit(final_features[0:1000],labels[0:1000])


[[ 0.39    0.61    0.     -0.8256]
 [ 0.308   0.692   0.     -0.9711]
 [ 0.211   0.695   0.094  -0.7757]
 ...
 [ 0.      1.      0.      0.    ]
 [ 0.      1.      0.      0.    ]
 [ 0.037   0.696   0.267   0.873 ]]
[0. 0. 0. ... 1. 1. 1.]


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
def pred_sentiment(file,no_lines):
  
  sentiment = np.zeros((no_lines,4))
  my_index = 0
  for line in file:
    sentiment[my_index] = get_sentiment(line)
    my_index = my_index+1
  return(sentiment)

In [0]:
def get_insults(file):
  
  t_hash = "#"
  webpage = "http"
  
  index = 0
  
  with open("2015insults_only.txt","w+") as file_out:
    for line in file:
      if t_hash not in line[0:2]:
        tokens = word_tokenize(line)
        if webpage in tokens:
          print(line[64:],end = '',file = file_out)
        
        

In [36]:
with open("2015LTinsultsLKML.tsv.txt","r") as temp_insults:
  get_insults(temp_insults)

with open("2015insults_only.txt","r") as test_insults:
  no_lines = get_index(test_insults)
with open("2015insults_only.txt","r") as test_insults:
  sent_test = pred_sentiment(test_insults,no_lines)

label_test = np.zeros((no_lines,1))
#print(sent_test)


neg: 0.072, neu: 0.885, pos: 0.042, compound: -0.2197, neg: 0.166, neu: 0.834, pos: 0.0, compound: -0.9068, neg: 0.14, neu: 0.797, pos: 0.063, compound: -0.6105, neg: 0.087, neu: 0.782, pos: 0.131, compound: 0.5332, neg: 0.276, neu: 0.646, pos: 0.078, compound: -0.9924, neg: 0.349, neu: 0.611, pos: 0.04, compound: -0.9772, neg: 0.455, neu: 0.545, pos: 0.0, compound: -0.875, neg: 0.283, neu: 0.611, pos: 0.106, compound: -0.9664, neg: 0.176, neu: 0.774, pos: 0.05, compound: -0.8074, neg: 0.302, neu: 0.566, pos: 0.133, compound: -0.7063, neg: 0.201, neu: 0.799, pos: 0.0, compound: -0.9718, neg: 0.221, neu: 0.779, pos: 0.0, compound: -0.6597, neg: 0.367, neu: 0.633, pos: 0.0, compound: -0.9549, neg: 0.259, neu: 0.696, pos: 0.045, compound: -0.8852, neg: 0.224, neu: 0.738, pos: 0.037, compound: -0.9854, neg: 0.2, neu: 0.8, pos: 0.0, compound: -0.7579, neg: 0.345, neu: 0.655, pos: 0.0, compound: -0.946, neg: 0.122, neu: 0.718, pos: 0.16, compound: -0.0772, neg: 0.289, neu: 0.546, pos: 0.165,

In [37]:
print(sent_test.shape)
print(clf.score(sent_test,label_test))
print(clf.score(final_features[1000:1600],labels[1000:1600]))

(47, 4)
0.7872340425531915
0.945


In [38]:
print(final_features[1101,0:])

[0.137  0.601  0.262  0.3182]


In [39]:
x = []
x = clf.predict(final_features[1000:1300])
print(x)
count = 0
for i in x:
  if i==0:
    print(count+692)
  count = count+1

[1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
696
704
718
745
754
757
780
798
855
874
925
935
937
940
951
968
